stages:
  - build_nmf
  - build_nmf_opssat
  - package
  - deploy
image: maven:3-openjdk-8

variables:
  NMF_HOME: /builds/nanosat-mo-framework/nmf-ops-sat
  MAVEN_OPTS: "-Dmaven.repo.local=$NMF_HOME/.m2/repository"

build_base:
  stage: build_nmf
  script:
    - git clone https://github.com/esa/CCSDS_MO_TRANS.git
    - cd CCSDS_MO_TRANS
    - git checkout tcp_bind_fix
    - mvn clean install -PESA
    - cd ..
    - git clone https://github.com/esa/nanosat-mo-framework.git
    - cd nanosat-mo-framework
    - if [ "$NMF_BRANCH" = "dev" ] && [[ $(git ls-remote --heads origin $CI_COMMIT_REF_NAME) ]]; then
    - git checkout $CI_COMMIT_REF_NAME
    - elif [ "$NMF_BRANCH" = "" ]; then
    - git checkout dev
    - else
    - git checkout $NMF_BRANCH
    - fi
    - mvn clean install
    - cd ..
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
    expire_in: 1 day

build_ground:
  stage: build_nmf_opssat
  script:
    - mvn clean install -Pground
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
      - $NMF_HOME/opssat-package/target/
    expire_in: 1 day

build_space:
  stage: build_nmf_opssat
  script:
    - mvn clean install -Pexp
  artifacts:
    paths:
      - $NMF_HOME/.m2/repository
      - $NMF_HOME/opssat-package/target/
    expire_in: 1 day

build_ipk:
  stage: package
  script:
    - mvn clean install -Pipk-build
  artifacts:
    paths:
      - $NMF_HOME/opssat-package/target/
    expire_in: 1 day

deploy_target1:
  stage: deploy
  when: manual
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-ops-sat-*/
    - scp -r home/ $T1USER@$TARGET1:~/nmf-ops-sat
    - ssh $T1USER@$TARGET1 "rm -rf /home/nmf/ /home/payloads-test/ && cp -r ~/nmf-ops-sat/* /home/"
    - ssh $T1USER@$TARGET1 "rm -rf ~/nmf-ops-sat"
  needs: ["build_ground"]

deploy_target2:
  stage: deploy
  rules:
    - if: '$AUTO_DEPLOY == "1"'
      when: always
    - if: '$AUTO_DEPLOY =~ "1"'
      when: manual
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-ops-sat-*/
    - ssh $T2USER@$TARGET2 "rm -rf nmf/"
    - scp -r home/nmf/ $T2USER@$TARGET2:~/nmf/
  needs: ["build_ground"]

deploy_target3_space:
  stage: deploy
  rules:
    - if: '$AUTO_DEPLOY == "1"'
      when: always
    - if: '$AUTO_DEPLOY =~ "1"'
      when: manual
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/
    - scp -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" nmf-ops-sat_*.ipk $T3USER@$TARGET3:~/
    - ssh -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" $T3USER@$TARGET3 "opkg --force-reinstall install nmf-ops-sat_*.ipk"
    - ssh -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" $T3USER@$TARGET3 "rm nmf-ops-sat_*.ipk"
  needs: ["build_ipk"]

deploy_target4:
  stage: deploy
  rules:
    - if: '$AUTO_DEPLOY == "1"'
      when: always
    - if: '$AUTO_DEPLOY =~ "1"'
      when: manual
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-ops-sat*/experimenter-package/home/exp000
    - scp -r * $T4USER@$TARGET4:$T4PATH/$NMF_USER
    - ssh $T4USER@$TARGET4 "chown $T4USER:$T4GROUP $T4PATH/$NMF_USER && chmod 644 $T4PATH/$NMF_USER/* && find $T4PATH/$NMF_USER -type d -exec chmod a+x {} \;"
  needs: ["build_space"]

deploy_target3_sim:
  stage: deploy
  rules:
    - if: '$AUTO_DEPLOY == "1"'
      when: always
    - if: '$AUTO_DEPLOY =~ "1"'
      when: manual
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cd opssat-package/target/nmf-ops-sat-*/home/nmf/
    - scp -r -o ProxyCommand="ssh -W %h:%p $JUSER@$JHOST" lib/ supervisor-sim/ $T3USER@$TARGET3:/home/nmf/
  needs: ["build_ground"]
